name: Run Tests
on:
    pull_request:
        types: [opened, reopened, synchronize]
jobs:
    lint:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            actions: read
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Install NodeJS
              uses: actions/setup-node@v4
              with:
                  node-version: "18.x"
            - name: Install pnpm
              uses: pnpm/action-setup@v3
              with:
                  version: 8
                  run_install: false
            - name: Get pnpm store directory
              shell: bash
              run: |
                  echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
            - uses: actions/cache@v3
              name: Setup pnpm cache
              with:
                  path: ${{ env.STORE_PATH }}
                  key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-pnpm-store-
            - run: pnpm run lint
    test:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            actions: read
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Install NodeJS
              uses: actions/setup-node@v4
              with:
                  node-version: "18.x"
            - name: Install pnpm
              uses: pnpm/action-setup@v3
              with:
                  version: 8
                  run_install: false
            - name: Get pnpm store directory
              shell: bash
              run: |
                  echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
            - uses: actions/cache@v3
              name: Setup pnpm cache
              with:
                  path: ${{ env.STORE_PATH }}
                  key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-pnpm-store-
            - run: pnpm test
            - run: pnpm run integration-test
